/**
 * Generates `src/generated/*` from `spec/openapi.v0.142.1.yml`:
 * - `schema.ts`: openapi-typescript's types;
 * - `operations.ts`: the operationId → method, path, response mode, auth table;
 * - `services/<tag>.ts`: one typed method per operation, grouped by tag;
 * - `services/index.ts`: the aggregator.
 *
 * Deterministic: same spec → same files. Usage: `pnpm codegen`.
 */
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { pathToFileURL } from "node:url";

import openapiTS, { astToString } from "openapi-typescript";
import { parse } from "yaml";

const ROOT = join(__dirname, "..");
/**
 * The SigNoz version the SDK mirrors is `signozVersion` in `package.json`, apart from the package's own
 * `version`: `signozVersion` 0.142.1 → spec `spec/openapi.v0.142.1.yml`. Without that version's spec,
 * the generator fails.
 */
const MIRRORED_VERSION: string = JSON.parse(readFileSync(join(ROOT, "package.json"), "utf8")).signozVersion;
const SIGNOZ_VERSION = `v${MIRRORED_VERSION}`;
const SPEC_PATH = join(ROOT, `spec/openapi.${SIGNOZ_VERSION}.yml`);
if (!existsSync(SPEC_PATH)) {
  throw new Error(
    `package.json's signozVersion is ${MIRRORED_VERSION}, but ${SPEC_PATH} does not exist: download docs/api/openapi.yml from SigNoz's ${SIGNOZ_VERSION} tag`
  );
}
const OUT = join(ROOT, "src/generated");
const HEADER = `// Generated by scripts/generate.ts from spec/openapi.${SIGNOZ_VERSION}.yml. Do not edit by hand.\n`;

const METHODS = ["get", "post", "put", "patch", "delete"] as const;

/**
 * The spec declares `200` without `content`, but the handler returns a streamed file
 * (CSV/NDJSON, `pkg/modules/rawdataexport/implrawdataexport/handler.go`).
 */
const RAW_OVERRIDES = new Set(["HandleExportRawDataPOST"]);

/** Session operations handled by the SDK's session manager. */
const SESSION_OPS: Record<string, "rotate" | "delete" | "login"> = {
  RotateSession: "rotate",
  DeleteSession: "delete",
  CreateSessionByEmailPassword: "login",
};

/** Names the namespaces cannot use (they are client properties). */
const RESERVED_NAMESPACES = new Set(["request", "session", "baseUrl", "tokens"]);

type Mode = "envelope" | "empty" | "raw" | "prometheus" | "redirect";

interface Op {
  id: string;
  method: string;
  path: string;
  tags: string[];
  mode: Mode;
  successCode?: string;
  auth: boolean;
  body?: { kind: "json" | "form"; required: boolean; contentType: string };
  hasPath: boolean;
  queryRequired: boolean;
  hasQuery: boolean;
  session?: "rotate" | "delete" | "login";
  summary?: string;
  description?: string;
  deprecated: boolean;
  security: string[];
}

// oxlint-disable-next-line typescript/no-explicit-any -- the spec is dynamic data
type Any = any;

const spec: Any = parse(readFileSync(SPEC_PATH, "utf8"), { maxAliasCount: -1 });

function camel(s: string): string {
  const parts = s.split(/[_\-\s]+/).filter(Boolean);
  return parts
    .map((p, i) => (i === 0 ? p.charAt(0).toLowerCase() + p.slice(1) : p.charAt(0).toUpperCase() + p.slice(1)))
    .join("");
}

function pascal(s: string): string {
  const c = camel(s);
  return c.charAt(0).toUpperCase() + c.slice(1);
}

function resolveRef(schema: Any): Any {
  if (schema?.$ref) {
    const name = String(schema.$ref).replace("#/components/schemas/", "");
    return spec.components.schemas[name];
  }
  return schema;
}

function classify(id: string, o: Any): { mode: Mode; code?: string } {
  if (RAW_OVERRIDES.has(id)) return { mode: "raw", code: "200" };
  const success = Object.entries(o.responses ?? {}).filter(([code]) => code.startsWith("2"));
  if (success.length === 0) return { mode: "redirect" };
  if (success.length > 1) throw new Error(`${id}: more than one 2xx response (${success.map(([c]) => c)})`);
  const [code, resp] = success[0] as [string, Any];
  const json = resp.content?.["application/json"];
  if (!json) {
    if (resp.content) throw new Error(`${id}: 2xx with non-JSON content ${Object.keys(resp.content)}`);
    return { mode: "empty", code };
  }
  if (json.schema?.$ref?.endsWith("/PrometheusSuccessResponseSchema")) return { mode: "prometheus", code };
  const schema = resolveRef(json.schema);
  if (schema?.properties?.status && schema?.properties?.data) return { mode: "envelope", code };
  throw new Error(`${id}: 2xx JSON without a {status,data} envelope and with no known mode`);
}

const ops: Op[] = [];
for (const [path, item] of Object.entries<Any>(spec.paths)) {
  for (const method of METHODS) {
    const o = item[method];
    if (!o) continue;
    const id: string = o.operationId;
    if (!id) throw new Error(`${method.toUpperCase()} ${path}: no operationId`);
    const { mode, code } = classify(id, o);
    const params: Any[] = [...(item.parameters ?? []), ...(o.parameters ?? [])];
    for (const p of params) {
      if (p.in !== "path" && p.in !== "query") throw new Error(`${id}: parameter in ${p.in} not supported`);
    }
    const security: Any[] | undefined = o.security;
    const auth = Array.isArray(security) && security.some((s) => "tokenizer" in s || "api_key" in s);
    const scopes = new Set<string>();
    for (const s of security ?? []) for (const v of Object.values<string[]>(s)) for (const x of v) scopes.add(x);
    let body: Op["body"];
    if (o.requestBody) {
      const content = o.requestBody.content ?? {};
      if (content["application/json"]) {
        body = { kind: "json", required: Boolean(o.requestBody.required), contentType: "application/json" };
      } else if (content["application/x-www-form-urlencoded"]) {
        body = {
          kind: "form",
          required: Boolean(o.requestBody.required),
          contentType: "application/x-www-form-urlencoded",
        };
      } else {
        throw new Error(`${id}: body ${Object.keys(content)} not supported`);
      }
    }
    ops.push({
      id,
      method: method.toUpperCase(),
      path,
      tags: o.tags?.length ? o.tags : ["default"],
      mode,
      successCode: code,
      auth,
      body,
      hasPath: params.some((p) => p.in === "path"),
      hasQuery: params.some((p) => p.in === "query"),
      queryRequired: params.some((p) => p.in === "query" && p.required),
      session: SESSION_OPS[id],
      summary: o.summary,
      description: o.description,
      deprecated: Boolean(o.deprecated),
      security: [...scopes],
    });
  }
}

// ---- name checks ----
const ids = new Set<string>();
for (const op of ops) {
  if (ids.has(op.id)) throw new Error(`duplicate operationId: ${op.id}`);
  ids.add(op.id);
}
const byTag = new Map<string, Op[]>();
for (const op of ops) {
  for (const tag of op.tags) {
    const list = byTag.get(tag) ?? [];
    list.push(op);
    byTag.set(tag, list);
  }
}
const tags = [...byTag.keys()].sort();
const namespaces = new Map<string, string>();
for (const tag of tags) {
  const ns = camel(tag);
  if (RESERVED_NAMESPACES.has(ns)) throw new Error(`tag ${tag} collides with a client property`);
  for (const [otherTag, otherNs] of namespaces) {
    if (otherNs === ns) throw new Error(`tags ${tag} and ${otherTag} produce the same namespace ${ns}`);
  }
  namespaces.set(tag, ns);
  const names = new Set<string>();
  for (const op of byTag.get(tag) ?? []) {
    const name = camel(op.id);
    if (names.has(name)) throw new Error(`method collision ${ns}.${name}`);
    names.add(name);
  }
}

// ---- emission ----
function jsdoc(op: Op, indent: string): string {
  const clean = (s: string) => s.replace(/\*\//g, "*\\/").trim();
  const lines: string[] = [];
  if (op.summary) lines.push(clean(op.summary));
  if (op.description && op.description !== op.summary) {
    if (lines.length) lines.push("");
    lines.push(...clean(op.description).split("\n"));
  }
  if (lines.length) lines.push("");
  lines.push(`\`${op.method} ${op.path}\` — operationId \`${op.id}\``);
  if (op.auth) lines.push(`Permission: ${op.security.length ? op.security.join(", ") : "authenticated user"}`);
  else lines.push("No `security` in the spec: sends the Bearer, but a 401 does not trigger a rotate.");
  if (op.mode === "raw") lines.push("Returns the `Response` with the streamed file (CSV or NDJSON).");
  if (op.mode === "redirect") lines.push("SSO callback: returns the redirect's `Response` without following it.");
  if (op.mode === "prometheus") lines.push("Prometheus format: returns `{status, data, warnings, infos}`.");
  if (op.session === "rotate") lines.push("Rotates the client's session and returns the new pair.");
  if (op.session === "delete") lines.push("Ends the session: after it the client makes no more authenticated calls.");
  if (op.deprecated) lines.push("@deprecated");
  return `${indent}/**\n${lines.map((l) => (l ? `${indent} * ${l}` : `${indent} *`)).join("\n")}\n${indent} */\n`;
}

function argsType(op: Op): { type: string; optional: boolean } | undefined {
  const O = `operations["${op.id}"]`;
  const fields: string[] = [];
  let required = false;
  if (op.hasPath) {
    fields.push(`path: ${O}["parameters"]["path"]`);
    required = true;
  }
  if (op.hasQuery) {
    const q = `${O}["parameters"]["query"]`;
    fields.push(op.queryRequired ? `query: ${q}` : `query?: ${q}`);
    required ||= op.queryRequired;
  }
  if (op.body) {
    const b = `NonNullable<${O}["requestBody"]>["content"]["${op.body.contentType}"]`;
    fields.push(op.body.required ? `body: ${b}` : `body?: ${b}`);
    required ||= op.body.required;
  }
  if (!fields.length) return undefined;
  return { type: `{ ${fields.join("; ")} }`, optional: !required };
}

function resultType(op: Op): string {
  if (op.session === "rotate") return "RotatedTokens";
  const O = `operations["${op.id}"]`;
  switch (op.mode) {
    case "envelope":
      return `${O}["responses"][${op.successCode}]["content"]["application/json"]["data"]`;
    case "prometheus":
      return `${O}["responses"][${op.successCode}]["content"]["application/json"]`;
    case "empty":
      return "void";
    case "raw":
    case "redirect":
      return "Response";
  }
}

rmSync(OUT, { recursive: true, force: true });
mkdirSync(join(OUT, "services"), { recursive: true });

// schema.ts (openapi-typescript is asynchronous; the rest of the emission is synchronous)
const schemaWritten = openapiTS(pathToFileURL(SPEC_PATH)).then((ast) =>
  writeFileSync(join(OUT, "schema.ts"), HEADER + astToString(ast))
);

// operations.ts
{
  let s = `${HEADER}import type { OperationSpec } from "../transport";\n\n`;
  s += `export const SIGNOZ_API_VERSION = "${SIGNOZ_VERSION}";\n\n`;
  s += "/** Every operation in the spec, by operationId. */\n";
  s += "export const OPERATIONS = {\n";
  for (const op of [...ops].sort((a, b) => a.id.localeCompare(b.id))) {
    const fields = [
      `id: "${op.id}"`,
      `method: "${op.method}"`,
      `path: "${op.path}"`,
      `mode: "${op.mode}"`,
      `auth: ${op.auth}`,
    ];
    if (op.body) fields.push(`body: "${op.body.kind}"`);
    if (op.session) fields.push(`session: "${op.session}"`);
    s += `  ${op.id}: { ${fields.join(", ")} },\n`;
  }
  s += "} as const satisfies Record<string, OperationSpec>;\n\n";
  s += "export type OperationId = keyof typeof OPERATIONS;\n\n";
  s += "/** Each operation's namespace and method on the client (the first tag; the others are aliases). */\n";
  s += "export const OPERATION_METHODS: Record<OperationId, readonly (readonly [string, string])[]> = {\n";
  for (const op of [...ops].sort((a, b) => a.id.localeCompare(b.id))) {
    const refs = op.tags.map((t) => `["${namespaces.get(t)}", "${camel(op.id)}"]`).join(", ");
    s += `  ${op.id}: [${refs}],\n`;
  }
  s += "};\n";
  writeFileSync(join(OUT, "operations.ts"), s);
}

// services/<tag>.ts
for (const tag of tags) {
  const ns = namespaces.get(tag) ?? tag;
  const list = byTag.get(tag) ?? [];
  const usesRotated = list.some((op) => op.session === "rotate");
  const usesOperations = list.some((op) => resultType(op).includes("operations[") || argsType(op));
  let s = HEADER;
  if (usesRotated) s += `import type { RotatedTokens } from "../../auth/session";\n`;
  s += `import type { RequestOptions, Transport } from "../../transport";\n`;
  s += `import type { Result } from "../../types";\n`;
  s += `import { OPERATIONS } from "../operations";\n`;
  if (usesOperations) s += `import type { operations } from "../schema";\n`;
  s += `\n/** Operations of the \`${tag}\` tag. */\n`;
  s += `export function create${pascal(tag)}Service(t: Transport) {\n  return {\n`;
  for (const op of list) {
    const args = argsType(op);
    const argDecl = args ? `args${args.optional ? "?" : ""}: ${args.type}, ` : "";
    const callArgs = args ? "args" : "undefined";
    s += jsdoc(op, "    ");
    if (op.session === "rotate") {
      // Goes through the session manager, which uses the current pair: no arguments or options.
      s += `    ${camel(op.id)}(): Promise<${resultType(op)}> {\n`;
      s += `      return t.call(OPERATIONS.${op.id}, undefined) as never;\n`;
      s += "    },\n";
      continue;
    } else {
      s += `    ${camel(op.id)}<O extends RequestOptions = RequestOptions>(${argDecl}options?: O): Promise<Result<O, ${resultType(op)}>> {\n`;
    }
    s += `      return t.call(OPERATIONS.${op.id}, ${callArgs}, options) as never;\n`;
    s += "    },\n";
  }
  s += "  };\n}\n";
  writeFileSync(join(OUT, "services", `${ns}.ts`), s);
}

// services/index.ts
{
  let s = `${HEADER}import type { Transport } from "../../transport";\n`;
  for (const tag of tags) {
    s += `import { create${pascal(tag)}Service } from "./${namespaces.get(tag)}";\n`;
  }
  s += "\n/** One namespace per tag in the spec. */\n";
  s += "export function createServices(t: Transport) {\n  return {\n";
  for (const tag of tags) s += `    ${namespaces.get(tag)}: create${pascal(tag)}Service(t),\n`;
  s += "  };\n}\n\n";
  s += "export type SignozServices = ReturnType<typeof createServices>;\n";
  writeFileSync(join(OUT, "services", "index.ts"), s);
}

const modes = ops.reduce<Record<string, number>>((acc, op) => {
  acc[op.mode] = (acc[op.mode] ?? 0) + 1;
  return acc;
}, {});
const generated = readdirSync(join(OUT, "services")).length;
void schemaWritten.then(() =>
  // oxlint-disable-next-line no-console -- the generator's report
  console.log(
    `${ops.length} operations, ${tags.length} tags (${generated} files in services/), modes: ${JSON.stringify(modes)}`
  )
);
