import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

type SidebarItem = Record<string, unknown> & { type?: string; label?: string; items?: SidebarItem[] };

/**
 * Every item a unique translation key: the path of labels that leads to it.
 *
 * TypeDoc names its categories after the kind of what they hold, so "Classes" and
 * "Interfaces" appear once per module. Docusaurus derives an item's translation key from its label, and
 * refuses to build a translated locale when two keys collide.
 */
function keyed(items: SidebarItem[], parent: string): SidebarItem[] {
  return items.map((item) => {
    const key = `${parent}/${item.label}`;
    if (item.type === "category" && item.items) return { ...item, key, items: keyed(item.items, key) };
    if (item.type === "doc") return { ...item, key };
    return item;
  });
}

/**
 * `docs/api/` is generated by docusaurus-plugin-typedoc on every English build (and gitignored),
 * with its own sidebar file beside it. Before the first build it does not exist yet.
 */
function apiSidebar(): SidebarItem[] {
  try {
    // oxlint-disable-next-line typescript/no-require-imports -- the generated sidebar is CommonJS, and may be absent
    return keyed(require("./docs/api/typedoc-sidebar.cjs") as SidebarItem[], "api");
  } catch {
    return [];
  }
}

const sidebars: SidebarsConfig = {
  guides: [
    "intro",
    {
      type: "category",
      label: "SDK",
      collapsed: false,
      items: ["sdk/overview", "sdk/authentication", "sdk/errors"],
    },
    {
      type: "category",
      label: "MCP server",
      collapsed: false,
      items: [
        "mcp/overview",
        "mcp/setup",
        "mcp/telemetry-tools",
        "mcp/alerts",
        "mcp/dashboards",
        "mcp/generic-tools",
        "mcp/configuration",
        "mcp/programmatic",
      ],
    },
    {
      type: "category",
      label: "CLI",
      collapsed: false,
      items: ["cli/overview", "cli/mcp-commands", "cli/windows"],
    },
    "contributing",
  ],
  // The translated sites exclude docs/api/ (see docusaurus.config.ts), so they get no API sidebar.
  ...((process.env.DOCUSAURUS_CURRENT_LOCALE ?? "en") === "en"
    ? { api: [{ type: "doc" as const, id: "api/index", label: "Overview" }, ...(apiSidebar() as never[])] }
    : {}),
};

export default sidebars;
